### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by YijiaWu1** [Cloufield/gwaslab#82]
Hi, 

I always have problem in installing the package. I attached the error message. 

<img width="925" alt="Screenshot 2024-03-17 at 11 43 45 PM" src="https://github.com/Cloufield/gwaslab/assets/140548738/af7bef63-335a-4b99-9741-b8203224ae6b">

**Comment by Cloufield** [comment]
Hi,
I guess I might need more information to troubleshoot here. Would you please share the version of python, gwsalab and which devide you are using?

**Comment by YijiaWu1** [comment]
the version of python is 3.11.0. I tried to do create the python3.9 environment as suggested (conda env create -n gwaslab_test -c conda-forge python=3.9), but failed. 
the version of gwaslab I tried to installed is 3.4.41.
My device is Macbook pro M2.
Thanks

**Comment by Cloufield** [comment]
Thanks! I think I may have seen a similar error before. It is probably caused by the limited compatibility support of Apple M chips. Would you please also show the full error message (which package caused the error)? 
I also prepared a  [DOCKER file for gwaslab](https://github.com/Cloufield/gwaslab/blob/main/docker/Dockerfile) that you can use to build images and use it as containers.

**Comment by alicepiller** [comment]
Hi, I got the same error. Here is the full error message:

(my_env) C:\Users\**>pip install gwaslab==3.4.45
Collecting gwaslab==3.4.45
  Using cached gwaslab-3.4.45-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: pandas!=1.5,>=1.3 in c:\users\**\appdata\local\anaconda3\envs\my_env\lib\site-packages (from gwaslab==3.4.45) (2.2.3)
Requirement already satisfied: numpy>=1.21.2 in c:\users\**\appdata\local\anaconda3\envs\my_env\lib\site-packages (from gwaslab==3.4.45) (2.0.2)
Collecting matplotlib!=3.7.2,>=3.5 (from gwaslab==3.4.45)
  Using cached matplotlib-3.9.4-cp39-cp39-win_amd64.whl.metadata (11 kB)
Collecting seaborn>=0.12 (from gwaslab==3.4.45)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scipy>=1.12 (from gwaslab==3.4.45)
  Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl.metadata (60 kB)
Collecting pySAM==0.22.1 (from gwaslab==3.4.45)
  Using cached pysam-0.22.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "C:\Users\**\AppData\Local\anaconda3\envs\my_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
        File "C:\Users\**\AppData\Local\anaconda3\envs\my_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
        File "C:\Users\**\AppData\Local\anaconda3\envs\my_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\**\AppData\Local\Temp\pip-build-env-9irixgoe\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\**\AppData\Local\Temp\pip-build-env-9irixgoe\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\**\AppData\Local\Temp\pip-build-env-9irixgoe\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\**\AppData\Local\Temp\pip-build-env-9irixgoe\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "C:\Users\**\AppData\Local\anaconda3\envs\my_env\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\**\AppData\Local\anaconda3\envs\my_env\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\**\AppData\Local\anaconda3\envs\my_env\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\**\AppData\Local\anaconda3\envs\my_env\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
